version: '3.8'
services:
  db:
    image: postgres:17
    container_name: running_tracker_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superparola123
      POSTGRES_DB: running_tracker
    ports:
      - "5432:5432"

  api:
    build: ./backend
    container_name: running_tracker_api
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/running_tracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: superparola123
    ports:
      - "8080:8080"